'use client'

import { cn } from '@/lib/utils'
import { Target, Database, Settings2, Server, Users, Shield, BarChart3 } from 'lucide-react'

const PILLAR_CONFIG = [
  { key: 'use_case_clarity', label: 'AI Use Cases', weight: 20, Icon: Target, focus: 'Do you know what problems AI should solve?' },
  { key: 'data_readiness', label: 'Data & Access', weight: 20, Icon: Database, focus: 'Is your data organized, connected, and accessible?' },
  { key: 'process_readiness', label: 'Workflows', weight: 20, Icon: Settings2, focus: 'Are your business processes documented and repeatable?' },
  { key: 'tech_infrastructure', label: 'Technology', weight: 15, Icon: Server, focus: 'Is your tech stack modern and cloud-connected?' },
  { key: 'people_culture', label: 'Team Readiness', weight: 15, Icon: Users, focus: 'Is your leadership and team ready for AI?' },
  { key: 'governance_compliance', label: 'Security & Compliance', weight: 10, Icon: Shield, focus: 'Do you have data privacy and security policies?' },
]

const TIERS = [
  { range: '0–25', tier: 'Exploring', desc: 'Early research stage', colorClass: 'text-red-700 border-red-200 bg-red-50/80', dot: 'bg-red-500' },
  { range: '26–50', tier: 'Experimenting', desc: 'Initial pilots underway', colorClass: 'text-amber-700 border-amber-200 bg-amber-50/80', dot: 'bg-amber-500' },
  { range: '51–75', tier: 'Scaling', desc: 'Expanding AI adoption', colorClass: 'text-primary border-primary/20 bg-primary/5', dot: 'bg-primary' },
  { range: '76–100', tier: 'Native', desc: 'AI-first organization', colorClass: 'text-emerald-700 border-emerald-200 bg-emerald-50/80', dot: 'bg-emerald-500' },
]

export default function ScoringMethodology() {
  return (
    <div className="card-base rounded-2xl overflow-hidden flex flex-col">
      <div className="p-5 pb-4 border-b border-border/60">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-primary/10 border border-primary/20 flex items-center justify-center">
            <BarChart3 className="w-4.5 h-4.5 text-primary" strokeWidth={1.5} />
          </div>
          <div>
            <h3 className="text-sm font-semibold text-foreground">Scoring Methodology</h3>
            <p className="text-xs text-muted-foreground mt-0.5">Weighted composite across 6 pillars</p>
          </div>
        </div>
      </div>

      <div className="p-5 flex-1 flex flex-col justify-between gap-5">
        {/* Pillar weights as a visual bar */}
        <div className="space-y-3">
          {PILLAR_CONFIG.map(({ key, label, weight, Icon, focus }) => (
            <div key={key} className="group">
              <div className="flex items-center justify-between mb-1">
                <div className="flex items-center gap-2">
                  <Icon className="w-3.5 h-3.5 text-primary/70" strokeWidth={1.5} />
                  <span className="text-xs font-medium text-foreground">{label}</span>
                </div>
                <span className="text-xs font-bold text-primary">{weight}%</span>
              </div>
              <div className="relative h-1.5 rounded-full bg-border/40 overflow-hidden">
                <div className="absolute inset-y-0 left-0 rounded-full bg-primary/30" style={{ width: `${weight * 5}%` }} />
              </div>
              <p className="text-[10px] text-muted-foreground mt-0.5 leading-snug">{focus}</p>
            </div>
          ))}
        </div>

        {/* Tier legend */}
        <div className="pt-4 border-t border-border/50">
          <h4 className="text-[10px] uppercase tracking-widest font-semibold text-muted-foreground mb-2.5">Score Tiers</h4>
          <div className="grid grid-cols-2 gap-2">
            {TIERS.map(({ range, tier, desc, colorClass, dot }) => (
              <div key={tier} className={cn('rounded-xl p-2.5 border', colorClass)}>
                <div className="flex items-center gap-1.5 mb-0.5">
                  <div className={cn('w-1.5 h-1.5 rounded-full', dot)} />
                  <span className="font-serif font-bold text-sm">{range}</span>
                </div>
                <div className="text-[10px] font-semibold">{tier}</div>
                <div className="text-[9px] opacity-70 mt-0.5">{desc}</div>
              </div>
            ))}
          </div>
        </div>

        <p className="text-[10px] text-muted-foreground/70 leading-relaxed">
          Overall Score = &Sigma;(Pillar Score &times; Weight). Generated by the agent after analyzing all content and survey responses.
        </p>
      </div>
    </div>
  )
}
